FROM node:22 as build-stage

# Enable yarn
RUN corepack enable

# Create app directory
RUN mkdir -p /webapp
WORKDIR /webapp

# Install app dependencies
COPY . /webapp
RUN yarn install

# Build the app
RUN yarn run build

# Production stage
FROM nginx as production-stage

COPY --from=build-stage /webapp/dist/. /usr/share/nginx/html

EXPOSE 80